springdoc:
  swagger-ui.path: /openapi/swagger-ui.html
  api-docs.path: /openapi/v3/api-docs
  packagesToScan: com.tutorhub
  pathsToMatch: /**
  override-with-generic-response: false

api:
  common:
    version: 1.0.0
    title: TutorHub API
    description: List of TutorHub endpoints
    contact:
      name: Tutorhub
      email: tutorhub.learnwithus@gmail.com