version: '3.0'

volumes:
  mongo-data:
    driver: local

services:

  postgresdb:
    image: postgres:16.2
    container_name: postgresdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tutorhub
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d