version: '3.0'

volumes:
  mongo-data:
    driver: local

services:
  mongo:
    image: 'mongo:focal'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db