logging:
  level:
    root: INFO
    com.tutorhub: DEBUG

spring:


  config:
    import:
      - optional:file:.env[.properties]
      - classpath:swagger/swagger-config.yaml


  datasource:
    url: jdbc:postgresql://${HOST}:${PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    changelog: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: tutorhub


  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        debug: false
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true


security:
  jwt:
    secret: ${JWT_SECRET}
    access: ${JWT_ACCESS_DURATION}
    activation: ${JWT_ACTIVATION_DURATION}
    refresh: ${JWT_REFRESH_DURATION}
    restore: ${JWT_RESTORE_DURATION}