CREATE TABLE IF NOT EXISTS USERS
(
    ID BIGSERIAL PRIMARY KEY,
    FULLNAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ENABLED BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS USERS_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLE VARCHAR(255) NOT NULL,
    PRIMARY KEY (USER_ID, ROLE),
    CONSTRAINT FK_USERS_ROLE_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE SEQUENCE USER_SEQ
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 1000
    CACHE 10;