CREATE TABLE IF NOT EXISTS PROGRESS
(
    ID BIGSERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS COURSES_INFO
(
    ID BIGSERIAL NOT NULL UNIQUE,
    COURSE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PROGRESS_ID BIGINT NOT NULL,
    PRIMARY KEY (COURSE_ID, USER_ID),

    CONSTRAINT FK_COURSES_INFO_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE NO ACTION,

    CONSTRAINT FK_COURSES_INFO_COURSES FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID) ON DELETE CASCADE ON UPDATE NO ACTION,

    CONSTRAINT FK_COURSES_INFO_PROGRESS FOREIGN KEY (PROGRESS_ID) REFERENCES PROGRESS (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);