CREATE TABLE IF NOT EXISTS PROGRESS
(
    ID BIGSERIAL NOT NULL UNIQUE,
    SUBMODULE_ID BIGINT NOT NULL,

    PRIMARY KEY (ID, SUBMODULE_ID),

    CONSTRAINT FK_PROGRESS_SUBMODULE FOREIGN KEY (SUBMODULE_ID) REFERENCES
    PROGRESS (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS COURSE_INFO
(
    ID BIGSERIAL NOT NULL UNIQUE,
    COURSE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,
    PROGRESS_ID BIGINT,
    PRIMARY KEY (COURSE_ID, USER_ID),

    CONSTRAINT FK_COURSE_INFO_USERS FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE ON UPDATE NO ACTION,

    CONSTRAINT FK_COURSE_INFO_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID) ON DELETE CASCADE ON UPDATE NO ACTION,

    CONSTRAINT FK_COURSE_INFO_PROGRESS FOREIGN KEY (PROGRESS_ID) REFERENCES PROGRESS (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);