CREATE TABLE IF NOT EXISTS CONTENT (
    ID BIGSERIAL PRIMARY KEY,
    CONTENT_TYPE VARCHAR(50) NOT NULL CHECK (CONTENT_TYPE IN ('VIDEO', 'IMAGE', 'TEXT')),
    CONTENT_TITLE VARCHAR(255) NOT NULL,
    CONTENT_DESCRIPTION VARCHAR(255) NOT NULL,
    CONTENT_URL VARCHAR(255) NOT NULL
);
