CREATE TABLE IF NOT EXISTS CONTENT (
    ID BIGSERIAL PRIMARY KEY,
    TYPE VARCHAR(50) NOT NULL CHECK (TYPE IN ('VIDEO', 'IMAGE', 'TEXT')),
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    URL VARCHAR(255) NOT NULL
);
