CREATE TABLE IF NOT EXISTS MODULE
(
    ID BIGSERIAL PRIMARY KEY,
    COURSE_ID BIGINT  NOT NULL,
    CONTENT_ID BIGINT,
    NAME VARCHAR(255) NOT NULL,

    CONSTRAINT FK_MODULE_COURSE FOREIGN KEY (COURSE_ID)
    REFERENCES COURSE (ID) ON DELETE CASCADE ON UPDATE NO ACTION,

    CONSTRAINT FK_MODULE_CONTENT FOREIGN KEY (CONTENT_ID)
    REFERENCES CONTENT (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS SUBMODULE
(
    ID BIGSERIAL PRIMARY KEY,
    MODULE_ID BIGINT  NOT NULL,
    CONTENT_ID BIGINT  NOT NULL,
    NAME VARCHAR(255) NOT NULL,

    CONSTRAINT FK_SUBMODULE_COURSE FOREIGN KEY (MODULE_ID)
    REFERENCES MODULE (ID) ON DELETE CASCADE ON UPDATE NO ACTION,

    CONSTRAINT FK_SUBMODULE_CONTENT FOREIGN KEY (CONTENT_ID)
    REFERENCES CONTENT (ID) ON DELETE CASCADE ON UPDATE NO ACTION
);
